#!/usr/bin/env python2

"""
Copyright 2015 Malte Splietker

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from argparse import ArgumentParser
import socket

def main():
    parser = ArgumentParser(description="Send N bytes over tcp.")
    parser.add_argument('receiver', metavar='Receiver', help='Receiving host')
    parser.add_argument('port', metavar='Port', help='Port receiver listens on')
    parser.add_argument('n_bytes', metavar='N', help='Number of bytes to send')
    args = parser.parse_args()

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((args.receiver, int(args.port)))

    n_bytes = int(args.n_bytes)
    block_size = 1024 * 1024
    chunk = "x" * block_size
    while n_bytes > 0:
        if n_bytes < block_size:
            chunk = "x" * n_bytes
        sock.sendall(chunk)
        n_bytes -= len(chunk)

    sock.sendall("1")
    sock.recv(1)
    sock.close()
    

if __name__ == "__main__":
    main()
